services:
    db:
        image: mysql/mysql-server:8.0
        volumes:
          - mysql_data:/var/lib/mysql
        environment:
            TZ: "Europe/Budapest"
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_DATABASE: $DB_NAME
        ports:
          - "${MYSQL_PORT}:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "-u$DB_USER", "-p$DB_PASSWORD",  "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
        restart: always
        networks:
            - app
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
            ssh:
                - default=$HOME/.ssh/id_rsa
        volumes:
          - runtime:/app/runtime
          - asset-cache:/app/www/assets/cache
        ports:
          - "${HTTP_PORT}:80"
        environment:
            TZ: "Europe/Budapest"
            VIRTUAL_HOST: umvc-app.local
            APPLICATION_ENV: $APPLICATION_ENV
            DB_DSN: $DB_DSN
            DB_NAME: $DB_NAME
            DB_USER: $DB_USER
            DB_PASSWORD: $DB_PASSWORD
            SAML_ADMIN_PASSWORD: $SAML_ADMIN_PASSWORD
            SAML_IDP: $SAML_IDP
            SAML_DISCO: $SAML_DISCO
            SAML_AUTH_SOURCE: $SAML_AUTH_SOURCE
        depends_on:
            db:
                condition: service_healthy
        restart: always
        networks:
            - app
            - reverseproxy
volumes:
    mysql_data:
    runtime:
    asset-cache:
networks:
    app:
    reverseproxy:
        external: true
        driver: overlay
